# Generated by Django 5.2.8 on 2025-12-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udemy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
